# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  environment:
    POETRY_VIRTUALENVS_IN_PROJECT: "true"
    POETRY_VIRTUALENVS_CREATE: "true"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - poetry install --only docs  # Using the docs dependency group

python:
  install:
    - method: poetry
      path: .

sphinx:
  configuration: docs/source/conf.py

